### PR TITLE
[ENH] allow to run analysis on specific files or session by filtering with bids.query

### PR DESCRIPTION
**Pull request by Remi-Gau**
- [x] add extra `opt.query` option that allows to run an analysis on certain files only
- [x] update getInfo to implement
- [x] update tests
- [x] update doc

If a dataset contains some files with the `acq` and `dir` entities then, the analysis can be run on those only by using the option
```matlab
  opt.query = struct('acq', '1p60mm', 'dir', 'PA');
```
where `'1p60mm'` and `'PA'` are the labels associated with those entities.

To run the analysis on the file that do NOT have those entities then use:
```matlab
  opt.query = struct('acq', '', 'dir', '');
```

To run the analysis on ALL the files, do NOT specify `opt.query`.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
fixes #198 
fixes #133

**Comment by marcobarilari** [comment]
LGTM, did not run though. Would also work for `opt.query = struct('ses', '003')`?

**Comment by Remi-Gau** [comment]
> LGTM, did not run though. Would also work for `opt.query = struct('ses', '003')`?

oh good call.

hum... I don't think it would work now. But I can make it work.

I raised the issue in #302 so we could get that done.

The way the the code works is that extra details for "query" do not overule how `getInfo` "filters" sessions.

See here: https://github.com/Remi-Gau/CPP_SPM/blob/69d309da889f8a76a2fbe2678767ce9f174e82a0/src/getInfo.m#L103

The "session" to query is defined above and I used the `setDefaults` function to update the things to query.

But this function will not overwrite a field if it already exists in a structure: so we just need to change that function so it can also overwrite the content of a field.

(BTW we should rename that `setDefaults` function because when used out of the `CheckOptions` context now, its name is super confusing)

**Comment by Remi-Gau** [comment]
Adding it to my to do for the lab hackathon tomorrow

**Comment by Remi-Gau** [comment]
@marcobarilari 

Made the changes so that you can run analysis on pre-specified sessions.

```
 opt.query = struct('ses', 'session_label');
```

or if you want to select several sessions 

```
 opt.query = struct('ses', {{'session_label1',  'session_label2'}});
```

Still want to test it on real data like openneuro `ds000114` but the demos work fine.

**Comment by Remi-Gau** [comment]
Actually, I can only test that easily after #310 is merged

**Comment by Remi-Gau** [comment]
oh hello `merge conflicts`, where have you been hiding all this time.

**Pull request merged**
