### PR TITLE
[ENH] workflow to reslice TPMs to func also create a mask for functional data

### PR DESCRIPTION
**Pull request by Remi-Gau**
merry Xmas @CerenB 

#  :christmas_tree:  :christmas_tree:  :christmas_tree:  :christmas_tree:

### CODE REVIEW

**Comment by CerenB** [comment]
perfect. The only thing I think of is, to add a note or documentation that user should use this function to create a mask. "Not only for QA but also creating a mask"
what do you think, @Remi-Gau ? Shall we keep a note for next documentation hackathon?

**Comment by Remi-Gau** [comment]
yup that's a good point. 

Actually it might be even better to rename the name of the workflow, no? 

`bidsCreateFunctionalMask` (or something like that) that has as "side effect" to relsice the TPMs rather than the other way around.

WDYT?

**Comment by CerenB** [comment]
sure, up to you! whichever is going to be the main usage of it.. for me, `createFunctionalMask` :) 
another option is we can split it into two functions.

**Comment by Remi-Gau** [comment]
Would rather rename it. Somehow something called `createFunctionalMask` seems more clear and useful than something called `resliceTPMs` (even when you know what TPM stands for.

We might want to add an error in the `functionalQA` part to remind people to reslice the TPM if the resliced versions cannot be found.

**Pull request merged**
