### PR TITLE
[FIX] fix unit issues in STC

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@marcobarilari 

This should do it.

But I will open another PR to implement some input check in the options selected by the userss.

**Comment by marcobarilari** [comment]
run it (with correct and wrong input) and the job file looks good to me, docs as well.

**Review by marcobarilari — APPROVED** [review]

**Comment by CerenB** [comment]
@marcobarilari did she see any substantial difference between before/after in the activity pattern?

**Comment by marcobarilari** [comment]
by 

> with correct and wrong input

I mean inducing the error (input in msec), that being said so far I never run the STC on our data cause did not find any solution to retrieve slice timing until today and in the localizers I saw nothing strange

**Pull request merged**
