### PR TITLE
[FIX] remove extra submodules and properly compute run level contrasts

### LINKED ISSUE #415: [BUG] test data "submodules" in the test folder
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

The data used for the tests should not have been committed as submodules.

- bids-matlab
- openneuro

https://github.com/cpp-lln-lab/CPP_SPM/tree/main/tests

### Current Behavior

Screenshot 2021-09-28 at 16 55 18

### Error message

_No response_

### Environment

_No response_

### Anything else?

_No response_

### LINKED ISSUE #416: [BUG] Only autocontrasts can be computed at the run level
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

specifying contrasts at the run level in the bids stats model should compute those contrasts 

### Current Behavior

nothing is computed

### Error message

_No response_

### Environment

_No response_

### Anything else?

the issue seems to be coming from there

https://github.com/cpp-lln-lab/CPP_SPM/blob/7750416b3f6b273814204131365baa6cd8d97649/src/subject_level/specifyContrasts.m#L147

### PR DESCRIPTION
**Pull request by Remi-Gau**
fixes #415 
fixes #416

### CODE REVIEW

**Comment by Remi-Gau** [comment]
This should also fix the fact that all tests were failing on `main`.

Required to update the bids-matlad and cpp_roi submodule and to a lot of tinckering.

**Comment by Remi-Gau** [comment]
@CerenB 

The tests seem to pass so you can go ahead and test that branch.

Mind you that you will have to update the bids-matlab and cpp_roi submodule if git kraken does not do it for you.

**Review by CerenB — APPROVED** [review]

**Comment by CerenB** [comment]
it works in gitkraken without any issues! I reviewed the changes for run level as well. now I'll run it on my local. 
thank you for tagging me, reviewing helps, especially to learn "where to look for" to understand how the code works.

**Comment by CerenB** [comment]
@Remi-Gau I see there's a variable change from "type" to "suffix". I got error for that. it cannot find "suffix". I cannot find it either, can you give me some pointers?
I was running FFX

`bidsFFX('specifyAndEstimate', opt, FWHM);
`
```
WORKFLOW: SUBJECT LEVEL GLM

Starting parallel pool (parpool) using the 'local' profile ...
connected to 4 workers.
 PROCESSING SUBJECT No.: 1 SUBJECT ID : 001 

 BUILDING JOB: specify subject level fmri model
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-001_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-001_events.tsv 
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-002_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-002_events.tsv 
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-003_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-003_events.tsv 
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-004_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-004_events.tsv 
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-005_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-005_events.tsv 
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-006_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-006_events.tsv 
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-007_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-007_events.tsv 
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-008_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-008_events.tsv 
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/s2wuasub-001_ses-001_task-PitchFT_run-009_bold.nii
reading the tsv file : /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/PitchFT/derivatives/cpp_spm/sub-001/ses-001/func/sub-001_ses-001_task-PitchFT_run-009_events.tsv 
Error using bids.create_filename (line 57)
We need at least a suffix to create a
filename.

Error in bidsFFX (line 71)
                                                                bids.create_filename(p))); 
```

**Comment by CerenB** [comment]
ok a bit further check also showed that` bids.report `function also fails on my local. 
When I went back in my branch to v.1.1.0 it works there. in the `bug-fix `branch, I get this error:

```
bids.report(opt.dataDir)
Error using ismember>ismemberR2012a (line 178)
Input A of class char and input B of class logical must be the
same class, unless one is double.

Error in ismember (line 87)
        lia = ismemberR2012a(A,B);

Error in bids.query>perform_query (line 226)
    if ~ismember(this_subject.name(5:end), subjects)

Error in bids.query (line 101)
  result = perform_query(BIDS, query, options, subjects,
  modalities, target);

Error in bids.report>select_session (line 297)
  sessions = bids.query(BIDS, 'sessions', 'sub', sub);

Error in bids.report (line 68)
  [ses, nb_ses] = select_session(BIDS, p, sub);
```

**Comment by Remi-Gau** [comment]
> I see there's a variable change from "type" to "suffix". I got error for that. it cannot find "suffix". I cannot find it either, can you give me some pointers?

arf... I must have overlooked some additional things to fix. 

In brief, when updating the bids-matlab version in use, it means that we now have to update some of the code.

The old version of bids matlab would use the term 'type' to refer to what in the BIDS world is a 'suffix' (the `_bold` at the end of your func file for example).

Am suprised that the system test did not crash because of that, but once again that highlights the need to have full code coverage in the test suite... #BrokenRecord 

Updating things now. Will run the full demos to make sure things are OK.

**Comment by Remi-Gau** [comment]
> ok a bit further check also showed that`bids.report`function also fails on my local.
> When I went back in my branch to v.1.1.0 it works there. in the `bug-fix `branch, I get this error:

That too is a bids-matlab issue: the report function is now broken and I must fix it. 

So temporarily comment it out. 

Will add a warning in our function in case people try to run it.

**Comment by Remi-Gau** [comment]
@CerenB Things should be fixed now.

**Comment by CerenB** [comment]
Wooop! calculating contrasts works on run level!

**Comment by Remi-Gau** [comment]
Awesome !!

Let's merge this baby

**Pull request merged**
