### PR TITLE
[FIX] bidsResults montage file naming fix

### PR DESCRIPTION
**Pull request by CerenB**
remove the dot in file naming string

### CODE REVIEW

**Review by Remi-Gau — APPROVED** [review]
LGTM

Tested it locally and used the opportunity to add an extra `_` to make the figure name easier to read. :stuck_out_tongue_winking_eye:

**Comment by CerenB** [comment]
hmm something is slightly odd, it saves the files (`.nii`, `.png`) with the correct naming but it also creates additional `.png` and `.csv` with default spm-way (as if spm is saying "This is the way"), e.g. `spm_2021Jan21_001.csv` for each contrast I have given in `opt.result.Steps(1).Contrast`
has any one faces with similar issue, @marcobarilari @fedefalag ?

**Comment by Remi-Gau** [comment]
Yes the renaming of the output only affects the montage and the `.nii` output.

If you check the `setBatResult` you will see that for csv and png, you can only have a boolean to say if you want that output or not. No option to rename it within the batch system.

If we want to rename those we would have to add some code for that or use the specific batch module for renaming files.

**Comment by CerenB** [comment]
naah I'm good :D what do you think?
I mean if these are the known issues, then I'm fine. Also the files are containing the p-value and contrast info when we open the .png so it is informative enough. 
I wanted to report in case these outcomes were not desired.

**Comment by marcobarilari** [comment]
Yes I confirm I have the same "issue"

**Pull request merged**
