### PR TITLE
bidsConcatBetaTmaps. fix

### PR DESCRIPTION
**Pull request by CerenB**
minor fixes with:
- how to call specifyContrast.m with the recent version
- comma in the structure
- use_schema option set to false otherwise it is crashing but maybe another way is better?

### CODE REVIEW

**Comment by CerenB** [comment]
all good!

**Comment by Remi-Gau** [comment]
OK will merge and apply those changes to the dev branch?

**Comment by CerenB** [comment]
> OK will merge and apply those changes to the dev branch?

should work on dev branch as well, yes. I did not do anything which would be problematic. 
That being said, is there anything I can do? e.g. PR to dev branch as well? (I'm currently working on main branch)

**Comment by Remi-Gau** [comment]
I already applied the patch to `dev` a couple of merge conflicts but nothing that I could not handle.

I have some failing tests so I will see what is up with that and also update to use the latest version of bids-matlab everywhere: this means that CPP-ROI will also start diverging so I will make a realease so we know which version the `main` branch of CPP_SPM is using. I don't your code to start breaking because of that.

**Pull request merged**
