### PR TITLE
[DOC] improve resuls doc and associated how to

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
fixes #469

**Comment by Remi-Gau** [comment]
pinging @fcerpe and @iqrashahzad14 for comments, suggestions and feedback

**Comment by fcerpe** [comment]
I think I just needed to pay more attention, the line to modify is already in getOption.
Sorry for the trouble

**Comment by iqrashahzad14** [comment]
@Remi-Gau I just saw the doc pdf of CPP_SPM and I think its amazing. For starters like me, it has all the information.
One thing I learnt by myself and with time is how and where are the results of the batches saved (in the derivatives folder) . Do we have it written somewhere? if not, can we include that also in the documentation?

**Comment by Remi-Gau** [comment]
> I think I just needed to pay more attention, the line to modify is already in getOption. Sorry for the trouble

no worries

If you struggled to find it then others would too.

**Comment by Remi-Gau** [comment]
> @Remi-Gau I just saw the doc pdf of CPP_SPM and I think its amazing. For starters like me, it has all the information. One thing I learnt by myself and with time is how and where are the results of the batches saved (in the derivatives folder) . Do we have it written somewhere? if not, can we include that also in the documentation?

Yeah this is something I would like to improve too.

I started adding something in the FFX section:

**Comment by Remi-Gau** [comment]
This is what the source `.rst` file would looks like.

What else would do you want to see in there ?

- where the `.mat` jobs are saved ?
- how to know where the subject level GLM folders are named and located?

**Comment by iqrashahzad14** [comment]
Maybe, what happens if we run same code twice? Do we have date and time stamps on the newer files or are we overwriting them?

**Comment by Remi-Gau** [comment]
in the vast majority of cases, if you have not touched anything, you will overwrite files, except:

- the job files (as a `.mat` and `.json`) has a time stamp: `YYYYMMDD_HHMM`

```
╰─(env) ⠠⠵ ls demos/MoAE/outputs/derivatives/cpp_spm-preproc/jobs/auditory/sub-01
20220110_1558_jobs_matlabbatch_SPM12_spatial_preprocessing-individual-IXI549Space.json
20220110_1558_jobs_matlabbatch_SPM12_spatial_preprocessing-individual-IXI549Space.mat
20220110_1616_jobs_matlabbatch_SPM12_spatial_preprocessing-individual-IXI549Space.json
20220110_1616_jobs_matlabbatch_SPM12_spatial_preprocessing-individual-IXI549Space.mat
```

- if you have used `saveOptions` at some point (most of the default `getOptions` templates include this as a last function call), then the options you have used to run this are saved with a time stamp too.

```
ls demos/MoAE/cfg 
options_date-202201050942.json                options_task-auditory_date-202201101206.json
options_date-202201050943.json                options_task-auditory_date-202201101214.json
options_date-202201050951.json                options_task-auditory_date-202201101222.json
options_date-202201112057.json                options_task-auditory_date-202201101331.json
```

---

Just realizing that the names and time stamp could used in a more consistent manner in those cases. Will open an issue to fix this.

**Comment by Remi-Gau** [comment]
If you want to set things up but not let SPM actually run the batches you can use the option:  

- `opt.dryRun = true()`

In most of other cases if you don't want to overwrite previous output, you will have to change the output directory.

For preprocessing, in most cases you would have to specify a different `opt.dir.ouput`. Things could be improved for some cases (have several output resolution for the normalization) to have everything in the same folder, but am not super keen to work on this as fmriprep covers those use cases pretty well.

For stats, you have a few more options. 

The output folder name should include the FWHM used on the BOLD images as well as info specified in the `Inputs` section of the BIDS stats model JSON file.:

```
$ ls demos/MoAE/outputs/derivatives/cpp_spm-stats/sub-01/stats       
                                  
task-auditory_space-IXI549Space_FWHM-6
```

But also the subject level GLM folder will include the Name of the BIDS stats model as description (`desc`) if this Name is not just the name of the task.

```matlab
  subLabel = '02';
  opt.taskName = 'nback';
  opt.space = 'individual';

  ffxDir = getFFXdir(subLabel, opt);

  expectedOutput = fullfile(getDummyDataDir('stats'), 'sub-02', 'stats', ...
                            'task-nback_space-individual_FWHM-6_desc-nbackMVPA');
```

Using this model:

```json
head tests/dummyData/models/model-nback_smdl.json
{
  "Name": "nback MVPA",                    <---- this gets appended to the folder name as description
  "BIDSModelVersion": "1.0.0",
  "Description": "for folder naming",
  "Input": {
    "task": "nback"
  }
  ...
```

**Comment by Remi-Gau** [comment]
> * the job files (as a `.mat` and `.json`) has a time stamp

Forgot to mention that the job `.json` files also contains heaps of info about the "environment" used to run that analysis (including the exact version of your OS, matlab, SPM, CPP_SPM: useful for methods writing).

**Comment by Remi-Gau** [comment]
will merge this and we can improve later

**Pull request merged**
